### ISSUE TITLE
Use ratio for scaling mapping area instead of absolute scaling

### ISSUE THREAD

**Issue by UnforeseenOcean** [PKBeam/Edda#125]
If you maximize the window and set it so the spectrogram section takes half or so of the mapping area and then resize the window, the spectrogram will cover the entire mapping area and cannot be adjusted or used. 
![1717420104](https://github.com/PKBeam/Edda/assets/11834016/06bd1e71-b6ab-45ff-8209-826dd1aaf91a)

A solution I'm proposing is to use the ratio of the spectrogram and note view (example shown below) by calculating how much area in the X-axis each part takes up and scaling them proportionally.
![1717419924](https://github.com/PKBeam/Edda/assets/11834016/95e7e021-6675-4af1-9b1b-94d2821f3e2e)

**Comment by Brollyy** [comment]
The setup for the editor grid is a little bit more complex, so just scaling all the columns on resize wouldn't work.
I was able to apply a workaround that should let the editor grid recover in most cases, but there are still some edge cases in which this situation can happen, unfortunately I'm not entirely sure how to handle them in WPF.
