### ISSUE TITLE
1.1.0 : crash on new / open map

### ISSUE THREAD

**Issue by cadavren** [PKBeam/Edda#14]
Hello hi !

I haven't been able to open nor create a new map. Happened to me both with NoRuntime and the other vers.
I don't really have any logs or any screen to provide since the program just close itself when I click either of the buttons.
I can't test to open via a recent map since I don't have any.

Previous version (1.0.3) works fine.

If I can get any infos or hand you anything that can be useful, please tell me !

Thank you for your hard work.

**Comment by PKBeam** [comment]
Please open Event Viewer in Windows and show me the output of any .NET Runtime Errors. (You may have to try to open Edda again to get the error to appear).

<img width="595" alt="image" src="https://user-images.githubusercontent.com/18737124/190881257-c6a41b30-89b3-4223-a2fb-af8eb88034aa.png">

**Comment by Allann** [comment]
This is an issue in `Helper.GetRagnarockMapFolder` because int.Parse fails with a NRE since you are returning Null from GetValueForKey.  Do you want help cleaning this and the codebase up, I'd be happy to help manage this.

**Comment by PKBeam** [comment]
> This is an issue in `Helper.GetRagnarockMapFolder` because int.Parse fails with a NRE since you are returning Null from GetValueForKey. Do you want help cleaning this and the codebase up, I'd be happy to help manage this.

Sure, it’d be great to get more people on this. Feel free to create a new issue for cleaning up the source, or if you want we can discuss it on Discord.
