### ISSUE TITLE
Opening the map through Recent Maps overwrites the map with blank data

### ISSUE THREAD

**Issue by UnforeseenOcean** [PKBeam/Edda#16]
This is due to the editor not exiting cleanly and leaving the thread behind, which overwrites recently opened maps with garbage. Terminating the rogue process rectifies this issue.

**Comment by PKBeam** [comment]
I can't figure out how to reproduce this.

Do you know what conditions cause the program to fail to close properly?

**Comment by UnforeseenOcean** [comment]
This is what I did when that happened:
1. A map is opened on one of two instances of the program (one most recent version, and another without the new environment)
2. The program is closed after selecting "Yes" on the save dialog
3. The other program is closed when the map is not opened

Also, using the program for a while causes it to consume an unnatural amount of memory, sometimes going up to 8GB and crashing the computer. It seems like scrubbing through the waveform causes it to cache everything in memory.

**Comment by Brollyy** [comment]
The same issue as #46 - will be resolved there.
