### ISSUE TITLE
48000Hz OGG Vorbis audio file causes crash when imported

### ISSUE THREAD

**Issue by UnforeseenOcean** [PKBeam/Edda#17]
This is more of an "oops" on my part as I forgot about the sampling rate on one of the files, however it is not handled gracefully in the app itself. Rather than throwing an error and rejecting it, it instead closes the entire editor.
This may cause issues down the line, so a metadata check could be useful to check whether or not this file can be read by the game (and the editor) itself.

To replicate: Convert any audio to 48000Hz audio and try to set it as the music.

**Comment by UnforeseenOcean** [comment]
Note: This seems to be more closely related to the fact that many songs/maps were opened beforehand. I tried this again and it didn't crash the first time, however, repeated tests caused the editor to crash with this being left on the log:

![IMG1667739506](https://user-images.githubusercontent.com/11834016/200172149-93a9806d-dff7-4e10-9b57-7d6148ab9ee7.png)

**Comment by PKBeam** [comment]
I have not been able to reproduce this yet. I tried resampling a file to 48K and repeatedly setting it as the song.

Are there any other error messages that you can find in the Event Viewer - like a stack trace?
If not, could you attach the problematic audio files and state how many repetitions causes the program to crash?

**Comment by UnforeseenOcean** [comment]
Try opening about 10~20 maps (or playing about 4 maps from start to finish in the editor) before attempting this, it looks like there's an issue with memory allocation.

**Comment by Brollyy** [comment]
@UnforeseenOcean With the fixes to #46 I've tried to bring down memory leaks as much as I could. 
If you can't replicate this issue anymore on 1.2.1 version, please close the issue.

**Comment by UnforeseenOcean** [comment]
No crash was detected with normal (< 6 minutes) audio. Closing the issue as completed.
