### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by RiedleroD** [PKBeam/Edda#18]
I think it should at least be possible to run this on linux via workarounds. Couldn't even get this to work on wine.

**Comment by PKBeam** [comment]
I managed to get Edda 1.1.0 running on Arch Linux using Proton.

Try running `protontricks --gui`, select one of your games, use the default wineprefix, then run Explorer and open Edda.

Seems to run okay but there's a bit of audio latency.

![Screenshot from 2023-01-05 18-29-06](https://user-images.githubusercontent.com/18737124/210725583-f2cd4acb-cc1f-45cd-b47d-233fa138c44b.png)
