### ISSUE TITLE
Improve the UX when changing Beat Division

### ISSUE THREAD

**Issue by Brollyy** [PKBeam/Edda#29]
Currently, when we want to change the beat division (which happens a lot when you're mapping rock/metal with notes on 6ths and 8ths), you have to change the value in the form on the right manually and then either click outside the input or play the song to update the lines.

It would be nice to improve the QoL there:
1. Pressing Enter should update the lines right away
2. There should be keyboard shortcuts which would increase/decrease the beat division by 1 and redraw the lines automatically.
    a. If the playback is on different BPM, the keyboard shortcut should update the beat division on the timing change instead - nice to have, but not that important.

I'll happily implement this myself, so you can assign this to me if you feel this would be a good improvement.

**Comment by PKBeam** [comment]
sounds good, go for it.

not sure about the performance impact of the keyboard shortcut but its worth investigating.

**Comment by Brollyy** [comment]
Released in 1.2.0 and works really well - thanks to @Nytilde for improving it to work with Timing Changes as well!
