### ISSUE TITLE
Edda not opening.

### ISSUE THREAD

**Issue by derpylz** [PKBeam/Edda#5]
Hi!

I would love to try Edda, but it does not open. After double clicking Edda.exe no window opens.
It pops up for less than a second in task manager, but then disappears again immediatly. There is no error message.

Are there any prerequesites that need to be installed first? Any hints on how to debug this?

Thanks!

**Comment by PKBeam** [comment]
Try the [latest release](https://github.com/PKBeam/Edda/releases/latest). (Download the larger .zip file - the one that *doesn't* say NoRuntime.)

If it doesn't open, try checking your antivirus settings and updating to the latest Windows 10 version.  

If it still doesn't open, try installing the [.NET 5.0 Desktop runtime](https://dotnet.microsoft.com/download/dotnet/5.0/runtime) and using it with the `NoRuntime` build.

If it *still* doesn't work, please open Event Viewer (Win+R, type in `eventvwr`), go to Windows Logs -> Application in the left sidebar and check for any errors related to Edda.

Thanks!

**Comment by derpylz** [comment]
Thanks for the hint with the Event Viewer! I found the error: Edda tried to open settings.txt but didn't have the rights. This was because I had extracted the program to a folder which needed Administrator privileges (somewhere in Program Files). So after copying everything to a different folder (somewhere in Documents), it worked like a charm!

Thank you for your swift help!
