### ISSUE TITLE
Bug: Edda will not attempt to change cover image when the cover image is already set

### ISSUE THREAD

**Issue by UnforeseenOcean** [PKBeam/Edda#50]
To replicate: Add the cover image, close the map and editor, open the editor again, and load the map. Then, try to load a new image to replace the one you've already set.
This bug can be worked around by either editing the `info.dat` to remove the mention of the image (so `"_coverImageFilename"` is set to `""`) or deleting the cover.jpg and replacing the file manually.

**Comment by Brollyy** [comment]
This was introduced when implementing #31
