### ISSUE TITLE
crash upon creating a new map.

### ISSUE THREAD

**Issue by unclegrandpalover** [PKBeam/Edda#6]
I got the latest no runtime version and tried to create a new map. after I chose my ogg, my cursor had the hourglass icon and then Edda crashed

**Comment by unclegrandpalover** [comment]
nevermind my ogg was messed up even though I thought it was vorbis and I did everything correctly

**Comment by unclegrandpalover** [comment]
ok nevermind again it only works when I use an ogg that's already been used by Edda. idk what kind of black magic sorcery you used for your ogg conversion but whatever it is didn't work for me.

**Comment by PKBeam** [comment]
Edda uses [NVorbis](https://github.com/NVorbis/NVorbis) for audio playback and FFmpeg for audio processing.

Can you send the offending .ogg file?

**Comment by PKBeam** [comment]
Someone else has reported a similar bug, which I've fixed in the latest release.

Please try that and let me know if you still have issues.

**Comment by unclegrandpalover** [comment]
I am using the latest version. also i got it to work by copying all the files from a different song that used this program. it worked but then just now when I tried to make a new difficulty, the program crashed and permanently deleted my 3 hours of charting. Also I can't send the file because github doesn't support it so I'll just put it in a zip file.
[Expurgation [Tricky Mod].zip](https://github.com/PKBeam/Edda/files/6994458/Expurgation.Tricky.Mod.zip)

**Comment by PKBeam** [comment]
I'm able to make a new map with the ogg file you've sent me.

Can you confirm that you're using Edda v0.4.0b3? (You can check in the Settings.)

Also, please make sure there aren't any issues with folder permissions - put Edda, the song file and any other related files in a non-privileged folder like your Downloads or Documents.
