### ISSUE TITLE
Bug: Song preview generation window has incorrect modality

### ISSUE THREAD

**Issue by UnforeseenOcean** [PKBeam/Edda#67]
Symptom: When the preview file is generated, the message box appears BEHIND the dialog, requiring you to either move the message box away from the original position or close the dialog then click on the message box.

![IMG1691408845](https://github.com/PKBeam/Edda/assets/11834016/5c2cb55d-8ed3-4286-98df-e5a53e7afef2)

Possible solution: Change the modality of the dialog box to less than that of what the message box currently has, or make it so when it finishes generating, the dialog closes.

**Comment by Brollyy** [comment]
This can be replicated by clicking Create Preview and then quickly changing focus to the main window while the spawned process is still generating the preview.
