### ISSUE TITLE
Feature request: slower playback

### ISSUE THREAD

**Issue by PoeHaH** [PKBeam/Edda#7]
Is there a way to play songs in slower speed?

**Comment by PKBeam** [comment]
Currently, no - I'll keep this in mind when I work on new features but I'm quite busy right now with other things so it will be a while.

**Comment by PoeHaH** [comment]
Hi Vincent,

Thanks for getting back to me and no problem at all. Edda remains the best tool for mapping. It's far simpler than anything else out there. Thanks for taking the time to make it!
