### ISSUE TITLE
Force cover image to be a square

### ISSUE THREAD

**Issue by Brollyy** [PKBeam/Edda#72]
Suggestion from PKshetlie.

The game doesn't support non-square covers - this is already enforced by RagnaCustoms, but it could also be checked by Edda to inform mappers ASAP.

**Comment by PKBeam** [comment]
should be simple to implement.

if the cover isn’t square we could look into ways to trim it. maybe crop to the largest contained square anchored to the top left corner, or something like that.

**Comment by Brollyy** [comment]
Probably better to crop it to a centered square
