### ISSUE TITLE
Feature Request: .SM, .SSC, or .osu conversion

### ISSUE THREAD

**Issue by Crimson-foxGITHUB** [PKBeam/Edda#8]
ArrowVortex isn’t just a timing tool, it’s the single best mapping tool I have ever used for any rhythm game, and this is coming from someone who has experience with more than 10 different editors. 

Not only is it’s workflow excellent, it has support for several VERY useful features Edda doesn’t have, like zooming out the map to manually adjust the view, faster difficulty switching, upscroll, better note selection, (using the Tab key instead of the mouse, and the mouse is a little janky in this regard) a built-in OGG converter, and easier preview-making.

It’s just got one big problem: none of the formats it exports to are compatible with Ragnarock: it can only export to .sm, .ssc, and .osu. Opening up the door to importing files from those formats also opens the gates to using timing points from songs with multiple BPM changes that have already been properly timed in other games, which allows people to completely skip the timing step on songs with a lot of BPM changes, or BPM fluctuation that’s common in rock and metal music.

**Comment by PKBeam** [comment]
This is a good idea.

Unfortunately this is a non-trivial amount of work and I don't have much time these days so I probably won't be able to implement this anytime soon.

If anyone else wants to try it I'd be happy to review a PR.

**Comment by Brollyy** [comment]
I'd like to work on this, at least on the support for .SM and .SSC, since they're pretty similar.

In terms of UI, I'd say it makes sense to introduce a third button on the start window, under Open Map, that will allow users to select an empty folder and then a simfile to convert. My only concern is that it will reduce the vertical space available for the Recent Maps section - do you see a better option?

**Comment by PKBeam** [comment]
That looks good. The icons are custom made but I can make one for importing.

We’ll also need to add the same import option to the menu bar in the main editor window, but that won’t be difficult.

**Comment by Crimson-foxGITHUB** [comment]
Just came back to this editor on the latest patch and here's what I have to say

Brollyy, you are an absolute gigachad for implementing this in. THANK YOU.
